---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.bestheme.ac.cn
  resources:
  - aliyuncertificatebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certs.bestheme.ac.cn
  resources:
  - aliyuncertificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.bestheme.ac.cn
  resources:
  - aliyuncertificates/finalizers
  verbs:
  - update
- apiGroups:
  - certs.bestheme.ac.cn
  resources:
  - aliyuncertificates/status
  verbs:
  - get
  - patch
  - update
