apiVersion: certs.bestheme.ac.cn/v1alpha1
kind: AliyunCertificate
metadata:
  labels:
    app.kubernetes.io/name: le-to-alicloud
    app.kubernetes.io/managed-by: kustomize
  name: aliyuncertificate-sample
spec:
  # TODO(user): Add fields here
