//go:build !ignore_autogenerated

/*
Copyright 2026 Hangzhou Yunqi Intelligence Technology Co., Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	certmanagerv1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	"github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificate) DeepCopyInto(out *AliyunCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificate.
func (in *AliyunCertificate) DeepCopy() *AliyunCertificate {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateBinding) DeepCopyInto(out *AliyunCertificateBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateBinding.
func (in *AliyunCertificateBinding) DeepCopy() *AliyunCertificateBinding {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunCertificateBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateBindingList) DeepCopyInto(out *AliyunCertificateBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AliyunCertificateBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateBindingList.
func (in *AliyunCertificateBindingList) DeepCopy() *AliyunCertificateBindingList {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunCertificateBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateBindingSpec) DeepCopyInto(out *AliyunCertificateBindingSpec) {
	*out = *in
	out.CertificateRef = in.CertificateRef
	in.Target.DeepCopyInto(&out.Target)
	if in.CredentialsRef != nil {
		in, out := &in.CredentialsRef, &out.CredentialsRef
		*out = new(LocalSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateBindingSpec.
func (in *AliyunCertificateBindingSpec) DeepCopy() *AliyunCertificateBindingSpec {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateBindingStatus) DeepCopyInto(out *AliyunCertificateBindingStatus) {
	*out = *in
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
	if in.LastObservedTime != nil {
		in, out := &in.LastObservedTime, &out.LastObservedTime
		*out = (*in).DeepCopy()
	}
	if in.CleanupStartedAt != nil {
		in, out := &in.CleanupStartedAt, &out.CleanupStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateBindingStatus.
func (in *AliyunCertificateBindingStatus) DeepCopy() *AliyunCertificateBindingStatus {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateList) DeepCopyInto(out *AliyunCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AliyunCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateList.
func (in *AliyunCertificateList) DeepCopy() *AliyunCertificateList {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AliyunCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateSpec) DeepCopyInto(out *AliyunCertificateSpec) {
	*out = *in
	in.CertificateTemplate.DeepCopyInto(&out.CertificateTemplate)
	in.Aliyun.DeepCopyInto(&out.Aliyun)
	in.Retention.DeepCopyInto(&out.Retention)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateSpec.
func (in *AliyunCertificateSpec) DeepCopy() *AliyunCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunCertificateStatus) DeepCopyInto(out *AliyunCertificateStatus) {
	*out = *in
	if in.EffectiveIssuerRef != nil {
		in, out := &in.EffectiveIssuerRef, &out.EffectiveIssuerRef
		*out = new(v1.IssuerReference)
		**out = **in
	}
	if in.Issuance != nil {
		in, out := &in.Issuance, &out.Issuance
		*out = new(IssuanceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = new(CertificateGeneration)
		(*in).DeepCopyInto(*out)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]CertificateGeneration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingUpload != nil {
		in, out := &in.PendingUpload, &out.PendingUpload
		*out = new(PendingUpload)
		(*in).DeepCopyInto(*out)
	}
	if in.CASProbedAt != nil {
		in, out := &in.CASProbedAt, &out.CASProbedAt
		*out = (*in).DeepCopy()
	}
	if in.CleanupStartedAt != nil {
		in, out := &in.CleanupStartedAt, &out.CleanupStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunCertificateStatus.
func (in *AliyunCertificateStatus) DeepCopy() *AliyunCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(AliyunCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliyunSpec) DeepCopyInto(out *AliyunSpec) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
	if in.UploadToCAS != nil {
		in, out := &in.UploadToCAS, &out.UploadToCAS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliyunSpec.
func (in *AliyunSpec) DeepCopy() *AliyunSpec {
	if in == nil {
		return nil
	}
	out := new(AliyunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingTarget) DeepCopyInto(out *BindingTarget) {
	*out = *in
	if in.FC3CustomDomain != nil {
		in, out := &in.FC3CustomDomain, &out.FC3CustomDomain
		*out = new(FC3CustomDomainTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingTarget.
func (in *BindingTarget) DeepCopy() *BindingTarget {
	if in == nil {
		return nil
	}
	out := new(BindingTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateGeneration) DeepCopyInto(out *CertificateGeneration) {
	*out = *in
	if in.CertID != nil {
		in, out := &in.CertID, &out.CertID
		*out = new(int64)
		**out = **in
	}
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
	in.UploadedAt.DeepCopyInto(&out.UploadedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateGeneration.
func (in *CertificateGeneration) DeepCopy() *CertificateGeneration {
	if in == nil {
		return nil
	}
	out := new(CertificateGeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateTemplate) DeepCopyInto(out *CertificateTemplate) {
	*out = *in
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(v1.IssuerReference)
		**out = **in
	}
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(certmanagerv1.X509Subject)
		(*in).DeepCopyInto(*out)
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]certmanagerv1.KeyUsage, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(certmanagerv1.CertificatePrivateKey)
		**out = **in
	}
	if in.SecretTemplate != nil {
		in, out := &in.SecretTemplate, &out.SecretTemplate
		*out = new(certmanagerv1.CertificateSecretTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateTemplate.
func (in *CertificateTemplate) DeepCopy() *CertificateTemplate {
	if in == nil {
		return nil
	}
	out := new(CertificateTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FC3CustomDomainTarget) DeepCopyInto(out *FC3CustomDomainTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FC3CustomDomainTarget.
func (in *FC3CustomDomainTarget) DeepCopy() *FC3CustomDomainTarget {
	if in == nil {
		return nil
	}
	out := new(FC3CustomDomainTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuanceStatus) DeepCopyInto(out *IssuanceStatus) {
	*out = *in
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(int)
		**out = **in
	}
	if in.RenewalTime != nil {
		in, out := &in.RenewalTime, &out.RenewalTime
		*out = (*in).DeepCopy()
	}
	if in.FailedIssuanceAttempts != nil {
		in, out := &in.FailedIssuanceAttempts, &out.FailedIssuanceAttempts
		*out = new(int)
		**out = **in
	}
	if in.LastFailureTime != nil {
		in, out := &in.LastFailureTime, &out.LastFailureTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuanceStatus.
func (in *IssuanceStatus) DeepCopy() *IssuanceStatus {
	if in == nil {
		return nil
	}
	out := new(IssuanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingUpload) DeepCopyInto(out *PendingUpload) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingUpload.
func (in *PendingUpload) DeepCopy() *PendingUpload {
	if in == nil {
		return nil
	}
	out := new(PendingUpload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionSpec) DeepCopyInto(out *RetentionSpec) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionSpec.
func (in *RetentionSpec) DeepCopy() *RetentionSpec {
	if in == nil {
		return nil
	}
	out := new(RetentionSpec)
	in.DeepCopyInto(out)
	return out
}
